export type RawPost = {
  post_name: string;
  post_parent: string;
  post_content: string;
  post_excerpt: string;
  post_status: "publish" | "not_published";
  post_password: string;
  menu_order: string;
  post_date: string;
  post_author: string;
  comment_status: "open" | "closed";
  sku: string;
  parent_sku: string;
  children: string;
  downloadable: string;
  virtual: string;
  stock: string;
  regular_price: string;
  sale_price: string;
  weight: string;
  length: string;
  width: string;
  height: string;
  tax_class: string;
  visibility: string;
  stock_status: "instock" | "outofstock";
  backorders: string;
  sold_individually: string;
  low_stock_amount: string;
  manage_stock: string;
  tax_status: "none" | "taxable";
  upsell_ids: string;
  crosssell_ids: string;
  purchase_note: string;
  sale_price_dates_from: string;
  sale_price_dates_to: string;
  download_limit: string;
  download_expiry: string;
  product_url: string;
  button_text: string;
  images: string;
  downloadable_files: string;
  product_page_url: string;
  "meta:total_sales": string;
  "tax:pwb-brand": string;
  "tax:product_type": string;
  "tax:product_visibility": string;
  "tax:product_cat": string;
  "tax:product_tag": string;
  "tax:product_shipping_class": string;
  "attribute:123": string;
  "attribute_data:123": string;
  "attribute:pa_رم": string;
  "attribute_data:pa_رم": string;
  "attribute:pa_رنگ": string;
  "attribute_data:pa_رنگ": string;
  "attribute:pa_سایز-مانیتور": string;
  "attribute_data:pa_سایز-مانیتور": string;
  "attribute:pa_سایز-کف-خواب": string;
  "attribute_data:pa_سایز-کف-خواب": string;
  "attribute:pa_طول-سیم": string;
  "attribute_data:pa_طول-سیم": string;
  "attribute:pa_قطر-خرطومی": string;
  "attribute_data:pa_قطر-خرطومی": string;
  "attribute:pa_گارانتی": string;
  "attribute_data:pa_گارانتی": string;
  "attribute:pa_attribute-8": string;
  "attribute_data:pa_attribute-8": string;
  "attribute:pa_brand": string;
  "attribute_data:pa_brand": string;
  "attribute:pa_color": string;
  "attribute_data:pa_color": string;
  "attribute:pa_inch": string;
  "attribute_data:pa_inch": string;
  "attribute:pa_pardazandeh": string;
  "attribute_data:pa_pardazandeh": string;
  "attribute:pa_playstation": string;
  "attribute_data:pa_playstation": string;
  "attribute:بلندگوی داخلی": string;
  "attribute_data:بلندگوی داخلی": string;
  "attribute:توان هر بلندگو": string;
  "attribute_data:توان هر بلندگو": string;
  "attribute:منبع تغذیه": string;
  "attribute_data:منبع تغذیه": string;
  "attribute:نقره ای": string;
  "attribute_data:نقره ای": string;
  "attribute:کیفیت تصویر": string;
  "attribute_data:کیفیت تصویر": string;
};
export type RawPostWithResponse = {
  rawPost: RawPost;
  response: object;
};
